### ISSUE TITLE
Todo: add security policy

### ISSUE THREAD

**Issue by DanielRuf** [Maikuolan/phpMussel#197]
**Is your feature request related to a problem? Please describe.**
We should create a SECURITY.md file which is supported now as policy to inform users how and for how long we support phpMussel with security patches and how they can contact us about security related issues.

**Describe the solution you'd like**
A SECURITY.md file with our policy for users of phpMussel.

**Describe alternatives you've considered**
Alternatively we can also add this to the docs and link to it.

**Additional context**
https://github.com/phpMussel/phpMussel/security/policy

**Comment by Maikuolan** [comment]
Definitely agree. :-)

Seen any SECURITY.md files in other repositories that could serve as good examples? I've looked around a little, but not sure whether there's many conventions (standard, de facto, or otherwise) for how to write this file yet. Otherwise, we should be able to easily come up with something ourselves anyway, but following conventions can be nice (and a little easier on end-users), when available.

There's actually one specific vulnerability from a while back (fixed since v1.6.0), that I'd sometimes felt would be good to write some kind of advisory for (but since it had already been fixed, since there's never been any evidence or reports of the vulnerability being exploited anywhere in the wild, and since I'd never been entirely sure about the best way to proceed with advisories, other than clearly documenting everything and doing whatever I can do make sure users regularly update, nothing ever came of it). GitHub now providing such a mechanism natively though, provides an opportunity to write something up, for both that specific vulnerability, as well as any like it that might potentially emerge in the future.

**Comment by DanielRuf** [comment]
> Seen any SECURITY.md files in other repositories that could serve as good examples?

It is a new feature which was announced today at GitHub Satellite. So I would have to look for one but I can check all other projects for this then.

**Comment by Maikuolan** [comment]
The [security policies and procedures for standardjs](https://github.com/standard/standard/blob/master/SECURITY.md) seems okay. Maybe something similar to theirs? Outlines the basics, conveys what it intends to convey, doesn't get bogged down with unnecessary detail (I've seen some others elsewhere that were quite extensive, some several pages long, with changelog copy/paste, etc).

**Comment by DanielRuf** [comment]
It's older and without the new template but should be sufficient.

Also see https://github.com/verdaccio/verdaccio/pull/1322 for more ideas that we can discuss.

**Comment by Maikuolan** [comment]
Some good ideas there. :-)

Wondering now, also, whether it would be worth registering an email address somewhere, dedicated for things like project vulnerability reports, disclosures, for sharing sensitive information, etc. Of course, we could always use an already existing email address too, but thinking about the different options anyway. 

Verdaccio (as well as most other security policies elsewhere, for that matter) includes an email address for reporting things via email. I think this is a good idea. But also, I've always had the idea hammered in over the years, about not listing our own email addresses anywhere in plain-text, where harvesters could collect them, due to the risk of spam and such. Creating a new, specially purposed email address for this could resolve that problem (to a certain extent, at least; could still be harvested, but at least, it wouldn't be our already existing email addresses being harvested).. though needing to regularly check yet another email account in case of new emails isn't super appealing. Setting up a simple redirect might be better, maybe.

**Comment by DanielRuf** [comment]
Let's discuss this in the coming days and I will list the relevant things that we would need then including recommendations =)

> where harvesters could collect them, due to the risk of spam and such

Not a problem for us. ;-) There are much more critical things to care about. I will prepare my recommendations then.

**Comment by Maikuolan** [comment]
Sounds good. :-)

**Comment by Maikuolan** [comment]
I've written and added a basic security policy just now (d6fa3be4606531e538000f59c28cec0670cba5f2 + 8606ee0a15a6c1d3aa784f52a960548cf5219a32). Any thoughts or any possible room for improvement that you can see?

**Comment by Maikuolan** [comment]
*Marking as implemented. Keeping the issue open until the next tagged release to invite further discussion if needed, suggestions for possible improvements, etc.*

**Comment by Maikuolan** [comment]
*New version tagged/released. Closing.*
