### ISSUE TITLE
Preview the alpha version of the english book!

### ISSUE THREAD

**Issue by BaseMax** [Maikuolan/phpMussel#199]
Hey,

I'm Max.
Teamwork by @Asrez :

![ScreenshotBook](https://user-images.githubusercontent.com/2658040/59139679-de166a00-89a9-11e9-9655-4e6ce99e4fa2.png)

```
Copyright 2019 Max Base
Last Updated: 26 May 2019 (2019.05.26).
Writing by Caleb Mazalevskis, Max Base
The first release, Jun 2019
```
Sorry, But I keep your name here. (Caleb Mazalevskis)

Not worry, because it's the first version.
and we will apply some new change...
https://github.com/BaseMax/phpMusselBook (You can make a star it if you love it)

You can preview the e-book file : [phpMussel.pdf](https://github.com/BaseMax/phpMusselBook/blob/master/phpMussel.pdf)
@nhlm @Maikuolan @petk @SuriyaaKudoIsc @DanielRuf

Regards,
Max

**Comment by BaseMax** [comment]
Hey @Maikuolan,

What's up?
@nhlm @Maikuolan @petk @SuriyaaKudoIsc @DanielRuf
This project has been leave?

Regards,
Max

**Comment by Maikuolan** [comment]
Hi @BaseMax,

> This project has been leave?

No, the project is still active. But, progress is slow, and sometimes we may take a little time to address everything, because our team is very small, we're just working on this when we have enough spare time for it, and our work is unpaid (voluntary basis, no money involved, and no current funding model, etc). Thanks for your patience. :-)

We invite and welcome all contributions to the project.

Currently, it seems the PDF just contains verbatim copy/paste from the README documentation, without any changes. I look forward to seeing what you can come up with, and I hope, that if you have some interesting information to contribute to the documentation, that you'll consider also sending some pull requests to add it to the original README documentation, too. The better our information can become, the more useful the package can become for our users.

Some things to note:
- The original README documentation uses "markdown", which doesn't render correctly in the PDF document (this could look a little strange to some human readers). A verbatim copy/paste from the README documentation into a PDF editor and saving it as a PDF document, mightn't be sufficient here; You may need to make manual changes, in places where the markdown doesn't render correctly, in order for human readers to be able to read it properly.
- You're welcome to adapt or modify the documentation (everyone has this right), but remember that this right, and the license which grants this right, must be maintained, recursively onward (this also means, if someone else adapts or modifies your adaptions and modifications, they too must maintain the license and granted rights for their adaptions and modifications). This is mainly for two reasons: (1) So that everyone can freely and openly benefit from it, and (2) to protect everyone legally, including you and me. (If a person or company uses our documentation, they can feel safe, knowing that we won't sue them, and it also makes it less likely that others might try to steal our work or claim rights over it, which protects us a little, and makes it easier to continue providing it freely and openly for everyone). Please consider making this clear in your publication.
- Currently, you've *published* a PDF document, but haven't added/written anything to it or changed any of the content yet. You become a *writer* when you add/write something to it (or an *editor* when you change/edit something already written). The distinction between these words, may seem insignificant to some people, but can be very significant to some people, too. ;-)

**Comment by Maikuolan** [comment]
*Closing for the purpose of cleaning up the issues page.*
