### ISSUE TITLE
Failed to open quarantine dir on fresh install

### ISSUE THREAD

**Issue by Costegillio** [Maikuolan/phpMussel#208]
### phpMussel version used.
2.1.0

### PHP version installed.
7.3.2

### Operating system.
Linux srv138-h-st.jino.ru 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64

---
## Issue
If you try to open quarantine tab on fresh installation it throws an error. _Manualy adding dir fixes the issue._

### PHP error
Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/phpMussel/vault/quarantine/): failed to open dir: No such file or directory in /phpMussel/vault/frontend_functions.php:912 Stack trace: #0 /phpMussel/vault/frontend_functions.php(912): RecursiveDirectoryIterator->__construct('/home/users/9/9...') #1 /phpMussel/vault/frontend.php(2629): {closure}(false) #2 /phpMussel/loader.php(153): require('/home/users/9/9...') #3 {main} thrown in /phpMussel/vault/frontend_functions.php on line 912

Thanx and good luck!

**Comment by Maikuolan** [comment]
Cheers. :-)

The directories existed in the repository by default in the past (i.e., < v2), but disappeared when I untracked their `.htaccess` files from the repository (because there weren't any other files in there by default, and Git isn't designed to track empty directories normally). Forgot to code for that accordingly. I'll sort that out now. :-)

**Comment by Maikuolan** [comment]
Fixed (3df41732c5700740fcd57f35fd50711d789df2e5 + ed1eed008c8a33a99767bf9d4c88e5a78afd86ab). :-)
