### ISSUE TITLE
'No problems found' on two test files

### ISSUE THREAD

**Issue by Costegillio** [Maikuolan/phpMussel#209]
### phpMussel version used (if known, please also include the exact commit hash).
2.1.0

### PHP version installed.
7.3.2

### Operating system used.
Linux srv138-h-st.jino.ru 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64

---
## Issue
'general_standard_testfile.txt' and 'ole_testfile.ole' from '_testFiles' dir are not detects on fresh installation with all signatures installed and activated..

### Steps to reproduce the behavior
* Fresh installation
* Installed and activated all signatures
* Checked all '_test Files' via 'Upload test' tab.
* All files has been catched exclude this two: 'general_standard_testfile.txt', 'ole_testfile.ole'.

---
### Relevant scan_log entry (if applicable).
> Checking 'general_standard_testfile.txt' (FN: e0a8291b; FD: 2c0f6de1):
-> No problems found.
Thu, 26 Sep 2019 12:30:13 +0300 Finished.
Thu, 26 Sep 2019 12:30:13 +0300 Started.
> Checking 'ole_testfile.ole' (FN: 1d191026; FD: 1b9c711f):
-> No problems found.
-> Checking 'ole_testfile.ole>ole_testfile.bin' (FN: ff64aeb8; FD: b6da61cd):
--> No problems found.
Thu, 26 Sep 2019 12:30:13 +0300 Finished.

### Relevant error_log entry (if applicable).
a:7:{s:10:"start_time";i:1569480607;s:8:"end_time";i:1569480607;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:1;s:11:"scan_errors";i:0;s:10:"detections";s:73:"Detected phpMussel-Testfile.ASCII.Standard (ascii_standard_testfile.txt)!";}
a:7:{s:10:"start_time";i:1569480613;s:8:"end_time";i:1569480613;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:1;s:11:"scan_errors";i:0;s:10:"detections";s:53:"Detected phpMussel-Testfile.CoEx (coex_testfile.rtf)!";}
a:7:{s:10:"start_time";i:1569480618;s:8:"end_time";i:1569480618;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:0;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:49:"Filetype blacklisted (exe_standard_testfile.exe)!";}
a:7:{s:10:"start_time";i:1569480623;s:8:"end_time";i:1569480623;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569480628;s:8:"end_time";i:1569480628;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569480631;s:8:"end_time";i:1569480631;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:0;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:49:"Filetype blacklisted (exe_standard_testfile.exe)!";}
a:7:{s:10:"start_time";i:1569480637;s:8:"end_time";i:1569480637;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569480646;s:8:"end_time";i:1569480646;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:1;s:11:"scan_errors";i:0;s:10:"detections";s:79:"Detected phpMussel-Testfile.Graphics.Standard (graphics_standard_testfile.gif)!";}
a:7:{s:10:"start_time";i:1569480650;s:8:"end_time";i:1569480651;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:1;s:11:"scan_errors";i:0;s:10:"detections";s:72:"Detected phpMussel-Testfile.HTML.Standard (html_standard_testfile.html)!";}
a:7:{s:10:"start_time";i:1569480658;s:8:"end_time";i:1569480658;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569480665;s:8:"end_time";i:1569480665;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:2;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569480673;s:8:"end_time";i:1569480674;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:1;s:11:"scan_errors";i:0;s:10:"detections";s:69:"Detected phpMussel-Testfile.PDF.Standard (pdf_standard_testfile.pdf)!";}
a:7:{s:10:"start_time";i:1569480682;s:8:"end_time";i:1569480682;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:0;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:49:"Filetype blacklisted (pe_sectional_testfile.exe)!";}
a:7:{s:10:"start_time";i:1569480689;s:8:"end_time";i:1569480689;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:1;s:11:"scan_errors";i:0;s:10:"detections";s:69:"Detected phpMussel-Testfile.SWF.Standard (swf_standard_testfile.swf)!";}
a:7:{s:10:"start_time";i:1569485212;s:8:"end_time";i:1569485213;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569487168;s:8:"end_time";i:1569487170;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569487661;s:8:"end_time";i:1569487662;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569488305;s:8:"end_time";i:1569488305;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:3;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569488481;s:8:"end_time";i:1569488482;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:2;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569489429;s:8:"end_time";i:1569489430;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569489907;s:8:"end_time";i:1569489907;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:2;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569489914;s:8:"end_time";i:1569489914;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}
a:7:{s:10:"start_time";i:1569490160;s:8:"end_time";i:1569490160;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:1;s:11:"scan_errors";i:0;s:10:"detections";s:72:"Detected phpMussel-Testfile.HTML.Standard (html_standard_testfile.html)!";}
a:7:{s:10:"start_time";i:1569490213;s:8:"end_time";i:1569490213;s:6:"origin";s:12:"176.59.144.x";s:15:"objects_scanned";i:3;s:16:"detections_count";i:0;s:11:"scan_errors";i:0;s:10:"detections";s:19:"Data not available.";}

**Comment by Maikuolan** [comment]
Thanks for reporting this. :-)

At the moment, `general_standard_testfile.txt` seems to be scanning correctly at my end, and blocked accordingly (i.e., haven't replicated the problem yet), but I'm still looking into that. I've managed to replicate the problem with `ole_testfile.ole` though; seems to be a bug in the way that some pre-conditions are processed prior to checking a file against a particular set of signatures (not sure when the bug was introduced.. the file was definitely scanning correctly in the past; I must've accidentally introduced something which broke it during refactoring or when introducing a new feature or something like that, I guess). Anyway.. Working on a fix for it now. :-)

**Comment by Maikuolan** [comment]
I believe I've fixed the aforementioned problem with `ole_testfile.ole` (4455f675a41b543aed660c4d257c8656cf846e25 + 8a1c8c2a25fb8e271dc6df33a6bc42507f97f274), but I haven't been able to replicate the problem with `general_standard_testfile.txt` yet.

When you've got a spare moment, mind updating to the latest commits, trying to scan the affected files again, and letting me know how it goes? Cheers. :-)

**Comment by Costegillio** [comment]
Here comes some fun:
* Fatal error: Uncaught Error: Function name must be a string in ~\phpMussel\vault\lang.php:67 Stack trace: #0 ~\phpMussel\loader.php(114): require() #1 {main} thrown in ~\phpMussel\vault\lang.php on line 67

It's throws at local and public servers.

**Comment by Costegillio** [comment]
BTW i've uninstalled all languages exclude english. M.b. it will be a clue?)

Thanks for your speed!

**Comment by Maikuolan** [comment]
Well.. That one has me a bit stumped. (At least, for the moment).

The particular line in question calls a generator to mark any optional YAML-based plugin L10N data for later inclusion alongside phpMussel's own L10N data when the YAML class loads it all. *Excerpt:*

```PHP
        foreach ($phpMussel['PluginIterator'](['Configured' => 'lang.en.yaml']) as $phpMussel['Plugin-L10N']) {
            $phpMussel['L10N']['Configured'][] = $phpMussel['Plugin-L10N']['Configured'];
        }
```

I'm definitely not seeing any non-string function calls in there at the moment.. but that's what the error's saying. Also not seeing the same error at my end though.

Do you have any phpMussel plugins installed at the moment? Any sub-directories under `vault/plugins`? (I know you mentioned earlier that it's a fresh installation, so I doubt there'll be anything in there, but asking anyway, just to cover all possible angles).

**Comment by Costegillio** [comment]
No, Caleb, i haven't any plugins. Same name folder haven't too)))

**Comment by Costegillio** [comment]
I've tried another one, fresh set-up, with default config and got the same error. Tried at php 7.2 and 7.3.

**Comment by Maikuolan** [comment]
Hm..  I'm using the same PHP versions in my dev environment, so I don't think that's the problem.

Actually, #206 mentions the same error message (albeit, the context was a little different, and the user didn't include any stack trace or any mention of the file or line number responsible for the error message). I wonder if the problem here might be similar? If you try changing the value of `cleanup` to `false`, does the error persist at your end?

(If there's no change, we'll keep digging further; but if it causes the error message to disappear, I might need to try doing something so that phpMussel can at least produce a different, more transparent error message for the situation in question, I think).

**Comment by Costegillio** [comment]
Even after setting 'cleanup' to 'false' error stil appears.

**Comment by Costegillio** [comment]
Playing:
![image](https://user-images.githubusercontent.com/29517737/65702687-a133c780-e0ad-11e9-9f35-53b0febdc941.png)

Output:
`NULL
Fatal error: Uncaught Error: Function name must be a string in ~\phpMussel\vault\lang.php:69 Stack trace: #0 ~\phpMussel\loader.php(114): require() #1 {main} thrown in ~\phpMussel\vault\lang.php on line 69`

**Comment by Maikuolan** [comment]
Definitely shouldn't be returning as null. o.0

I'll see if I can rope some others into taking a look at it. Might have some better luck with more eyes on it.

**Comment by Costegillio** [comment]
Ok, i'll stay in touch.
Thank you so much!

**Comment by Costegillio** [comment]
It was totally my fault and i'm really sorry for wasting your time, Caleb!

I've reinstalled phpMussel in same dir as before and marked what i've got cloud sync for that folder. Seems what the sync app has rewrite some files with older one...

After fresh installation (real fresh at now))) in a new dir everything works.

And as you wrote before: everything detects exclude 'general_standard_testfile.txt':

`-> Checking 'ole_testfile.ole>ole_testfile.bin' (FN: ff64aeb8; FD: b6da61cd):
--> Detected phpMussel-Testfile.OLE.Standard!
Thu, 26 Sep 2019 19:11:32 +0300 Finished.
Thu, 26 Sep 2019 19:12:17 +0300 Started.
> Checking 'general_standard_testfile.txt' (FN: e0a8291b; FD: 2c0f6de1):
-> No problems found.`

**Comment by Maikuolan** [comment]
Woo-hoo! Found the problem. :-)

I've just compared my local downstream against the remote upstream for the testfiles, and have discovered an EOL discrepancy exists for some of them (including the general standard testfile). Seeing as the specific signature for catching the general standard testfile crosses over multiple lines, that discrepancy would be causing it to not be caught. The EOL used for the files must've been automatically updated at some point during somebody's commit, whether mine or somebody else's, I don't know; but anyway, now that I know what's causing it, it'll be easy to fix it.

Thinking I'll just update the signatures, rather than trying to fix the EOL used by the testfiles, in case the same thing happens again (and probably much easier if all files are using the same EOL anyway).

Anyway, I'll reply again as soon as I've pushed the new signatures.

**Comment by Maikuolan** [comment]
Bit delayed getting them pushed due to having some visitors over yesterday, but anyway, I've pushed them now (https://github.com/phpMussel/Signatures/commit/30dfd2fd9c5dff6fa47b45d4b8ae8f3903a9676e). Updating to the latest signatures should resolve the problem with `general_standard_testfile.txt` not being detected properly before. :-)

(`misc/phpmussel.db.gz` is the only file of any real consequence to this issue, but I figure, if I'm updating one of them, I may as well update the others while I'm at it at the same time).

**Comment by Maikuolan** [comment]
Marking as *fixed* and closing. Let me know if the problem still persists, and if so, we can reopen the issue accordingly. Cheers. :-)
