### ISSUE TITLE
No such file or directory in ~phpMussel\vault\functions.php on line 5071

### ISSUE THREAD

**Issue by Costegillio** [Maikuolan/phpMussel#210]
Greetings! Sorry for posting another one issue :(

### phpMussel version used.
2.1.0

### PHP version installed.
7.3.9

### Operating system used.
 Windows NT 6.3 build 9600 (Windows 8.1 Professional Edition) AMD64

---
## Issue
Well, if i try to log-in at front-end (fresh installation) at the top of the page php throws 2 warns:
* Warning: mkdir(): No such file or directory in ~\phpMussel\vault\functions.php on line 5071
* Warning: Cannot modify header information - headers already sent by (output started at ~phpMussel\vault\functions.php:5071) in ~phpMussel\vault\frontend.php on line 350

Also i cant load any of tabs because it's redirects me on login page.

### Expected behavior
Same zip file extracted at public server loads fine.

Thanks for your work, good luck!

**Comment by Maikuolan** [comment]
No problem; I would rather know about it so that I can fix it, than not know about and end up having these problems gradually affect more and more people over time. '^.^

Anyway, found the problem here; I recently added some code to guard against missing directories, but it doesn't seem to be quite working as expected and needs a little work. Working on it now. :-)

**Comment by Maikuolan** [comment]
Fixed (3df41732c5700740fcd57f35fd50711d789df2e5 + ed1eed008c8a33a99767bf9d4c88e5a78afd86ab). :-)
