### ISSUE TITLE
Virus/Malware not detected

### ISSUE THREAD

**Issue by patrickbussmann** [Maikuolan/phpMussel#214]
I downloaded this EICAR virus test PDF file.
https://blog.didierstevens.com/2015/08/28/test-file-pdf-with-embedded-doc-dropping-eicar/

Then I installed phpMussel via Composer.

`composer require phpmussel/phpmussel`

And then I added all things together.

    <?php
    
    require_once 'vendor/autoload.php';
    require 'vendor/phpmussel/phpmussel/loader.php';
    
    var_dump($phpMussel['Scan'](__DIR__ . '/pdf-doc-vba-eicar-dropper.pdf', true, true));

And then I get this output.

```
Wed, 25 Mar 2020 22:22:04 +0100 Started.
> Checking '[...]/pdf-doc-vba-eicar-dropper.pdf' (FN: 56ffab5d; FD: 7d521036):
-> No problems found.
Wed, 25 Mar 2020 22:22:04 +0100 Finished.
```

When I do the same with my computer virus scanner its directly detected as Eicar-Test-File.

On the updates page (http://localhost/vendor/phpmussel/phpmussel/loader.php) I installed and activated this additional signatures:

- ClamAV complex extended signatures.
- ClamAV standard signatures.
- ClamAV filename signatures.
- ClamAV ELF signatures.
- ClamAV PDF signatures.
- ClamAV PDF regex signatures.
- phpMussel PDF signatures.

So whats the mistake here?

Thanks in Advance.

**Comment by DanielRuf** [comment]
See also https://github.com/phpMussel/phpMussel/issues/148#issuecomment-358022839

> I downloaded this EICAR virus test PDF file

Not sure if we support this type of file (embedded in PDF). The txt file should work.

**Comment by Maikuolan** [comment]
Hi Patrick,

> So whats the mistake here?

No mistake, AFAICT.

Unfortunately, phpMussel's ability to detect macros is quite limited at the moment, and much more work needs to be done before phpMussel's macro detection abilities could be considered as a standard resembling that of other, more well-known anti-virus solutions.

Because the particular EICAR sample in this case is generated by a VBA script, embedded within a DOC file, embedded within a PDF file, in order to be able to detect the EICAR sample, we'd first need to be able to detect that there's a DOC file embedded within the PDF file, extract the DOC file, then detect the VBA script inside the DOC file, extract that, then analyse it determine that it generates the EICAR sample and so on.

To a certain extent, phpMussel can already detect objects within certain types of files and then extract those objects to analyse them, but there are many file formats that it isn't yet fully aware of, isn't yet capable of extracting objects from and so on. Basically, the reason the sample wasn't detected in this case is because current functionality isn't sufficient.

I would like to be able to move forward in regards to improving phpMussel's macro detection abilities, but my own skills and knowledge in that particular area are somewhat limited, so to do so, new people would need to be brought into the project to fill that knowledge and skill gap, I think.

In terms of recognising EICAR: The necessary signatures are already there, and phpMussel should be capable of detecting the original EICAR sample, when it isn't embedded inside anything else or generated by anything else.
