### ISSUE TITLE
Error when activate signatures

### ISSUE THREAD

**Issue by marianomachao** [Maikuolan/phpMussel#216]
### phpMussel version used:
`v2@aab251349999722b450bc10f30c524bb7c1eafe3
`
**PHP & OS used:**
7.2.24-0 ubuntu0.18.04.3
---
## Issue
I get these errors when I use manual scanning (like this `$phpMussel['Scan'](...)`).
I renamed 'vault/upload.php' file so library does not scan automatically.
When I deactivate signatures, error disappears.

`PHP message: PHP Warning:  strpos() expects parameter 1 to be string, array given in /home/ubuntu/s1_cdn/lib/phpMussel/vault/functions.php on line 2112
PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to {closure}() must be of the type string, array given, called in /home/ubuntu/s1_cdn/lib/phpMussel/vault/functions.php on line 2113 and defined in /home/ubuntu/s1_cdn/lib/phpMussel/vault/functions.php:293`

These are the signatures I have installed: 

`active='clamav.cedb,clamav.htdb,clamav_elf_regex.db,clamav_exe_regex.db,clamav_java_regex.db,clamav_pdf_regex.db,clamav_swf.db,clamav.db,clamav.mdb,clamav_email.db,clamav_graphics.db,clamav_ole.db,clamav_regex.db,clamav_swf_regex.db,clamav.fdb,clamav.ndb,clamav_email_regex.db,clamav_graphics_regex.db,clamav_ole_regex.db,clamav_regex.htdb,switch.dat,clamav.hdb,clamav_elf.db,clamav_exe.db,clamav_java.db,clamav_pdf.db,clamav_regex.ndb'
`

Any idea what it could be?
Thanks a lot!

**Comment by Maikuolan** [comment]
Thanks for reporting this. :-)

I noticed that `switch.dat` was included in your list of active signature files. The problem is immediately replicated at my end when I do the same at my end, which reveals a small bug: That file is being interpreted as a signature file. phpMussel shouldn't be interpreting that file as a signature file, regardless of whether it's listed in the active signature files list, because phpMussel signature files contain a small "magic number", which should normally help to prevent non-signature files being accidentally processed due to being listed in the active signature files list, but unfortunately, that file also matched positive for that "magic number".

I've just now pushed a new commit to fix that bug (https://github.com/phpMussel/phpMussel/commit/9171d31895cad10c52d3d055da106d0e842ea894). Removing `switch.dat` from the list should fix the problem for the moment, and updating to the latest commit should prevent the problem from reoccurring (and should also fix the problem, even if it isn't removed from the list). :-)
