### ISSUE TITLE
Migrate to GHA

### ISSUE THREAD

**Issue by DanielRuf** [Maikuolan/phpMussel#217]
We might try GitHub Actions which is typically faster, supports many Actions and can be easily extended.

**Comment by Maikuolan** [comment]
Sounds like a good idea. I'm really not yet familiar with GitHub Actions at all though, so, I'll need to learn some new things, I think. '^.^

I noticed the commit https://github.com/phpMussel/phpMussel/commit/3d99b4e4dd203162911b1b90fa86f50abe8027e1, tied to the [workflow you created a little earlier](https://github.com/phpMussel/phpMussel/actions/runs/122960768), but it doesn't seem to be connected to any branches (or, at least, HEAD not updated at v2). Orphaned commit..? Or GHA just automatically pushes commits, without attaching them to branches..? I'm wondering, for experimenting with the workflow a little, or for making any changes at GHA, whether to push new commits (i.e., orphaned and/or no branch = not clear where to target the commits), or whether it would be better to not push commits at all, instead just doing everything directly through the GHA UI only.

**Comment by Maikuolan** [comment]
Anyway, I'll do some reading (e.g., documentation) to try to get a better understanding of how GHA works, how to use it, etc. It will be good if we can get this working for us.

**Comment by DanielRuf** [comment]
The commit that you saw was from the new code scanning feature (currently beta) of GitHub to scan for CWEs in code. I force-pushed the rebased head without this commit because they do not yet support PHP.

**Comment by DanielRuf** [comment]
There is no GHA UI to push commits. There is just an Action editor. You set it up once and configure it like Travis CI using yaml, merge / commit the config to the branch and then every PR, push, set interval triggers it (the new CI setup).

**Comment by Maikuolan** [comment]
Cool cool. :-)

**Comment by Maikuolan** [comment]
Adding "Help Wanted" label.

(Might be worth looking at this from a v3 perspective, too; i.e., for repositories like phpMussel/Core, phpMussel/Web, phpMussel/CLI, phpMussel/FrontEnd, etc).

**Comment by Maikuolan** [comment]
*Removing "Help Wanted" and "Planning" labels. Adding "Work-In-Progress."*

GHA-based testing implemented to v3 Core ([`3ef2361`](https://github.com/phpMussel/Core/commit/3ef23617fabe9d4f483abea458e8bc2757114855)).

v1 and v2 haven't been touched yet (working on that at the moment).

Would like to be able to add eicar tests to it too, at some point, if possible. Not entirely sure yet how to do that while also being able to safeguard against the AVs at the systems where clones/installs reside generating false positives from those clones/installs due to samples. Low priority though. I'll add that in at some point, if/when I can figure it out.

**Comment by Maikuolan** [comment]
Done. :-) 

*Marking as "Implemented" and closing.*
