### ISSUE TITLE
Why is there some JSON?

### ISSUE THREAD

**Issue by jamieduk** [Maikuolan/phpMussel#221]
Please use this template when reporting bugs, problems, issues, etc.

### phpMussel version used (if known, please also include the exact commit hash).
e.g., 1.0.0-DEV@c8778924df2cb94d40796a0876005c46b711e76e

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
e.g., cgi-fcgi

### PHP version installed (`<?php echo phpversion(); ?>`).
e.g., 7.1.0

### Operating system used (`<?php echo php_uname(); ?>`).
e.g., Linux localhost 2.4.21-0.13mdk #1 Fri Mar 14 15:08:06 EST 2003 i686

---
## Issue
Please describe the problem here.

### Expected behavior
What should normally happen?

### Actual behavior
What is actually happening?

### Steps to reproduce the behavior
* step 1
* step 2
* step 3
* …

### Last known working version without this issue.
---

**Comment by Maikuolan** [comment]
Hi @jamieduk,

When you mention "json bs", are you referring to the `composer.json` file, or something else?

If you're referring to the `composer.json` file, that file is necessary as a means of being able to install phpMussel (v3 and onward) via Composer ([more information about that is provided in the documentation](https://github.com/phpMussel/Docs/blob/master/readme.en.md#20-installing-with-composer)). If you don't use Composer, you can safely ignore it and/or delete it from your copy of phpMussel (phpMussel itself does not need that file), but you won't be able to install or update from Composer without that file.

If you're referring to something else, you'll need to elaborate a little bit more in order to be able to provide a better answer for you.

phpMussel from v3 and onward require Composer, since a majority of phpMussel users nowadays prefer a Composer-based implementation, but if you don't want to use Composer to install phpMussel, one possible solution is to just download phpMussel v2 or v1 instead (v0 is dead, but all other major versions, i.e., v1, v2, and v3, are all still actively maintained and should be perfectly fine to use). You can fetch the latest versions of the raw files for v1 or v2 by switching to the v1 or v2 branches at this repository and then downloading from the respective branch of the desired major version. Another possible solution is by installing from the phpMussel [examples](https://github.com/phpMussel/Examples) repository (note that since the examples repository is provided only as a convenience and isn't used for development, the raw files won't be in that repository's tree, but instead are attached as ZIPs to the tags at that repository).

**Comment by DanielRuf** [comment]
Please fill out the issue template and provide all relevant details so we understand what you mean.

**Comment by DanielRuf** [comment]
> If you're referring to something else, you'll need to elaborate a little bit more in order to be able to provide a better answer for you.

This.

Closing this issue as it contains no complete bug report / issue description.
When you have updated the issue description we can reopen it and properly answer your question with the relevant information.
