### ISSUE TITLE
 Detects only .exe files.

### ISSUE THREAD

**Issue by Costegillio** [Maikuolan/phpMussel#222]
Greetings!

Another one fresh install another one problems)

Actually after fresh manual install phpMussel and installing/activating signatures via web-interface it doesn't detect any files from '_testfiles' folder exclude of '.exe files'.

### phpMussel version used (if known, please also include the exact commit hash).
2.1.5

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
apache2handler

### PHP version installed (`<?php echo phpversion(); ?>`).
7.4

### Operating system used (`<?php echo php_uname(); ?>`).
Linux srv78-h-st.jino.ru 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64

---
## Debug information

> <?php die; ?>
> Tue, 29 Sep 2020 13:17:58 +0300 Started.
> > Checking 'ascii_standard_testfile.txt' (FN: ce76ae7a; FD: c4f668fa):
> -> No problems found.
> Tue, 29 Sep 2020 13:17:59 +0300 Finished.
> Tue, 29 Sep 2020 13:17:59 +0300 Started.
> > Checking 'coex_testfile.rtf' (FN: b0e404dc; FD: c44e0020):
> -> No problems found.
> Tue, 29 Sep 2020 13:17:59 +0300 Finished.
> Tue, 29 Sep 2020 13:17:59 +0300 Started.
> > Checking 'exe_standard_testfile.exe' (FN: bc2b0816):
> -> Filetype blacklisted.
> Tue, 29 Sep 2020 13:17:59 +0300 Finished.
> Tue, 29 Sep 2020 13:17:59 +0300 Started.
> > Checking 'general_standard_testfile.txt' (FN: e0a8291b; FD: 2c0f6de1):
> -> No problems found.
> Tue, 29 Sep 2020 13:17:59 +0300 Finished.
> Tue, 29 Sep 2020 13:17:59 +0300 Started.
> > Checking 'graphics_standard_testfile.gif' (FN: fa02d6a4; FD: 31dcb0b4):
> -> No problems found.
> Tue, 29 Sep 2020 13:17:59 +0300 Finished.
> Tue, 29 Sep 2020 13:17:59 +0300 Started.
> > Checking 'hash_testfile_md5.txt' (FN: 7207cc85; FD: e983902b):
> -> No problems found.
> Tue, 29 Sep 2020 13:17:59 +0300 Finished.
> Tue, 29 Sep 2020 13:17:59 +0300 Started.
> > Checking 'hash_testfile_sha256.txt' (FN: 2bd41253; FD: 36e7c5a4):
> -> No problems found.
> Tue, 29 Sep 2020 13:17:59 +0300 Finished.
> Tue, 29 Sep 2020 13:17:59 +0300 Started.
> > Checking 'hash_testfile_sha1.txt' (FN: c2eb70ba; FD: 6061c089):
> -> No problems found.
> Tue, 29 Sep 2020 13:17:59 +0300 Finished.
> Tue, 29 Sep 2020 13:17:59 +0300 Started.
> > Checking 'html_standard_testfile.html' (FN: 20df694f; FD: 48e4ea2b):
> -> No problems found.
> Tue, 29 Sep 2020 13:18:00 +0300 Finished.
> Tue, 29 Sep 2020 13:18:00 +0300 Started.
> > Checking 'ole_testfile.ole' (FN: 1d191026; FD: 1b9c711f):
> -> No problems found.
> -> Checking 'ole_testfile.ole>ole_testfile.bin' (FN: ff64aeb8; FD: b6da61cd):
> --> No problems found.
> Tue, 29 Sep 2020 13:18:00 +0300 Finished.
> Tue, 29 Sep 2020 13:18:00 +0300 Started.
> > Checking 'pdf_standard_testfile.pdf' (FN: 6d1c7c10; FD: 8c05e37f):
> -> No problems found.
> Tue, 29 Sep 2020 13:18:00 +0300 Finished.
> Tue, 29 Sep 2020 13:18:00 +0300 Started.
> > Checking 'pe_sectional_testfile.exe' (FN: 51114ec6):
> -> Filetype blacklisted.
> Tue, 29 Sep 2020 13:18:00 +0300 Finished.
> Tue, 29 Sep 2020 13:18:00 +0300 Started.
> > Checking 'swf_standard_testfile.swf' (FN: 1c2de39d; FD: e0cfb75b):
> -> No problems found.
> Tue, 29 Sep 2020 13:18:00 +0300 Finished.
> Tue, 29 Sep 2020 13:18:16 +0300 Started.
> > Checking 'ascii_standard_testfile.txt' (FN: ce76ae7a; FD: c4f668fa):
> -> No problems found.
> Tue, 29 Sep 2020 13:18:16 +0300 Finished.
> Tue, 29 Sep 2020 13:18:29 +0300 Started.
> > Checking 'coex_testfile.rtf' (FN: b0e404dc; FD: c44e0020):
> -> No problems found.
> Tue, 29 Sep 2020 13:18:29 +0300 Finished.
> Tue, 29 Sep 2020 13:18:45 +0300 Started.
> > Checking 'ole_testfile.ole' (FN: 1d191026; FD: 1b9c711f):
> -> No problems found.
> -> Checking 'ole_testfile.ole>ole_testfile.bin' (FN: ff64aeb8; FD: b6da61cd):
> --> No problems found.
> Tue, 29 Sep 2020 13:18:45 +0300 Finished.
> Tue, 29 Sep 2020 13:20:32 +0300 Started.
> > Checking 'hash_testfile_md5.txt' (FN: 7207cc85; FD: e983902b):
> -> No problems found.
> Tue, 29 Sep 2020 13:20:32 +0300 Finished.
> Tue, 29 Sep 2020 13:20:38 +0300 Started.
> > Checking 'exe_standard_testfile.exe' (FN: bc2b0816):
> -> Filetype blacklisted.
> Tue, 29 Sep 2020 13:20:38 +0300 Finished.
>

**Comment by Costegillio** [comment]
Ok, after switching to v3 everything works fine. Thx!

**Comment by Maikuolan** [comment]
Greetings, @Costegillio. :-)

I'm glad to hear that the problem has been resolved, and glad to hear that the problem seems to not exist in v3 (based on that it's working now since switching to v3).

I noticed this issue earlier, but didn't reply right away, since I didn't have any particular ideas offhandedly regarding what might've been the root cause of the problem (since, if correctly installed/activated, it certainly *should* be scanning correctly), and I'd wanted to try to think up what would be the best way to approach the issue before recommending anything particular.

I'm guessing there must be some differences between the way I wrote the v2 codebase versus the v3 codebase which is causing the problem, though I'm not quite sure yet exactly what. I'll investigate a little more in my spare time if I can find some leads, and if I can get anywhere with it, I'll try to push a fix for the problem (eventually). Slightly less concerning if the problem only affects v2 and lower, and not v3, but anyway, regardless, thanks for mentioning the problem here with this issue (good to know about these things, since I don't always spot these problems myself).

Of course, if the problems appears again, or if there's any other strange behaviour even after switching, let me know.

Cheers.

**Comment by Costegillio** [comment]
Greetings, @Maikuolan !

Glad to see what you still work on your project and it grows in positive and bugless way. Hope you've enjoyed your new version (as i) and you've learned something new and useful.

Good luck and many thx for your work!
