### ISSUE TITLE
ZIP file containing safe png file getting flagged by Image Chameleon

### ISSUE THREAD

**Issue by shadowstriker15** [Maikuolan/phpMussel#223]
Please use this template when reporting bugs, problems, issues, etc.

### phpMussel version used (if known, please also include the exact commit hash).
Core and web at 3.0

### PHP SAPI used.
fpm-fcgi

### PHP version installed.
7.2.31

### Operating system used.
Darwin MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar 4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

---
## Issue
When scanning an uploaded zip containing a safe image file (a .png file) the upload is getting flagged as an image chameleon attack. However, when I upload the image alone, not compressed, the upload is successful.

### Expected behavior
The zip should pass inspection with no errors.

### Actual behavior
The zip file is being flagged as a image chameleon attack.

### Steps to reproduce the behavior
* Tried using a different image file
* Tried a different zip file (still gets flagged)

**Comment by Maikuolan** [comment]
Hi @shadowstriker15,

I've spent some time this morning attempting to replicate the problem at my end (creating some arbitrary png files, zipping them under arbitrary conditions, using store mode only without compression, using maximum compression possible, etc), but thus far haven't been successful. Would it be possible for you to attach one of the affected zip files here, so that I can try scanning it at my end to help replicate the problem? My current thinking is that maybe there's a difference in the kinds of filenames produced by our respective zip software upon zipping the png files, or that there's some kind of difference in the way they're being compressed, or something like that, which could be the reason why I haven't been able to replicate the problem yet.

Cheers. :-)

**Comment by shadowstriker15** [comment]
Hey @Maikuolan,

Thank you for the quick response! I am compressing the image file by using the default compression possible on a Mac. I've included the files in this reply.
![Test](https://user-images.githubusercontent.com/1342626/94694863-e6ab5600-02fa-11eb-915a-b1071fd228c4.png)
[Test.zip](https://github.com/phpMussel/phpMussel/files/5305994/Test.zip)

**Comment by shadowstriker15** [comment]
I also can't seem to get `delete_on_sight` working when set to true; if the uploaded file fails the scan it isn't deleted automatically.

**Comment by shadowstriker15** [comment]
Additionally, the `delete_on_sight`

**Comment by Maikuolan** [comment]
Cheers. :-)

Since looking at the included zip file, I've found the problem. It seems that Mac OS X creates thumbnails for the PNG files with some metadata attached, these thumbnails hidden alongside the files themselves, and with a similar naming schema. Since the thumbnails themselves aren't actually PNG files, but look like PNG files, they're getting flagged by the image chameleon attack detection.

IMO, the best solution for this would be to hardcode a bypass for these thumbnails into the phpMussel scanner, to prevent the problem from occurring. I'll commit some changes and reply again shortly.

**Comment by Maikuolan** [comment]
I've committed a fix for the aforementioned problem just now ([`v1`](https://github.com/phpMussel/phpMussel/commit/4fc4aa9302b454214df20fa9e06c3fd7e3c78777)+[`v2`](https://github.com/phpMussel/phpMussel/commit/0a516ff44db8d1259e7d8395071cc16386c07741)+[`v3-Core`](https://github.com/phpMussel/Core/commit/31856423f1e1a08b7158c101341f884168f246a1)), so after updating, at least that should be okay now (but let me know if the problem still persists, of course).

> I also can't seem to get `delete_on_sight` working when set to true; if the uploaded file fails the scan it isn't deleted automatically.

I'll investigate that and reply again within the next few hours. :-)

**Comment by shadowstriker15** [comment]
The zip uploaded successfully without it being flagged as a chameleon attack. Thank you for being so quick on this.

**Comment by nhlm** [comment]
Sounds like a binary thumbnail issue. EXIF allow to attach thumbnails to images (so called thumbnail chain containers) instead of storing them at the file system. So you do have a some-fancy-image.png and a various set of thumbnails is "compiled" into the EXIF data. Some anti-malware engines detect this as false-positive chameleons.

A huge help to avoid such detections would be to strip off exif content from the file as a inbound filter of your application. The most web applications do not need the full set of EXIF contents of the file, so you can easily drop them and reduce the filesize when storing them at the used storage. Stripping binary content from EXIF is also a wise action to avoid spreading malware as a containment of images. So, it might be something to consider when handling image uploads in general. Passing them to gdlib and storing them then at the storage would do this.

kindest regards

**Comment by Maikuolan** [comment]
> I'll investigate that and reply again within the next few hours. :-)

(Just to touch base: My apologies for not replying earlier, when I'd said that I would. Became a little busy with other things. Haven't looked further into that yet, but still planning on doing so, and will reply when I get a moment. Keeping this issue open until that time).

**Comment by shadowstriker15** [comment]
> > I'll investigate that and reply again within the next few hours. :-)
> 
> (Just to touch base: My apologies for not replying earlier, when I'd said that I would. Became a little busy with other things. Haven't looked further into that yet, but still planning on doing so, and will reply when I get a moment. Keeping this issue open until that time).

No worries

**Comment by Maikuolan** [comment]
> I also can't seem to get `delete_on_sight` working when set to true; if the uploaded file fails the scan it isn't deleted automatically.

So, I found the time to test this a little further tonight, but I haven't been able to replicate the problem at my end thus far.

Actually.. I may need to update the docs, because currently, it describes `delete_on_sight` as only applying to file uploads, but as well as testing the problem at hand with normal file uploads, I also tested the problem at hand using the phpMussel API (i.e., explicitly scanning specific files other than uploads), and discovered that when enabled, it seems to also delete those files, too (so, though not being able to successfully replicate the problem at hand, that's possibly a separate problem with `delete_on_sight` that I'll need to deal with at some point.. but whether to change code to conform with the description at the docs, or whether to change the docs to reflect the current behaviour of the code..? I'm not sure yet; that's something I'll need to have a think about. But anyway, since it's unrelated to the problem at hand, I'll leave it at that for the moment). '^.^

Just to confirm: I assume that when you encountered the problem at hand at your end, you were just uploading files in the usual manner (i.e., through a form in your browser)? Or were you using the built-in API, or something else entirely? Just to cover all bases, in case my assumption is wrong, to better narrow things down for trying to replicate the problem at hand.

**Comment by shadowstriker15** [comment]
> > I also can't seem to get `delete_on_sight` working when set to true; if the uploaded file fails the scan it isn't deleted automatically.
> 
> So, I found the time to test this a little further tonight, but I haven't been able to replicate the problem at my end thus far.
> 
> Actually.. I may need to update the docs, because currently, it describes `delete_on_sight` as only applying to file uploads, but as well as testing the problem at hand with normal file uploads, I also tested the problem at hand using the phpMussel API (i.e., explicitly scanning specific files other than uploads), and discovered that when enabled, it seems to also delete those files, too (so, though not being able to successfully replicate the problem at hand, that's possibly a separate problem with `delete_on_sight` that I'll need to deal with at some point.. but whether to change code to conform with the description at the docs, or whether to change the docs to reflect the current behaviour of the code..? I'm not sure yet; that's something I'll need to have a think about. But anyway, since it's unrelated to the problem at hand, I'll leave it at that for the moment). '^.^
> 
> Just to confirm: I assume that when you encountered the problem at hand at your end, you were just uploading files in the usual manner (i.e., through a form in your browser)? Or were you using the built-in API, or something else entirely? Just to cover all bases, in case my assumption is wrong, to better narrow things down for trying to replicate the problem at hand.

Yes, I am uploading the files through a form. I am first uploading the file to a tmp directory and running `$Web->scan()` on the directory after each upload. I was assuming the `delete_on_sight` option would delete the file the scan failed on.

**Comment by shadowstriker15** [comment]
Wondering if the `delete_on_sight` functionality has been looked into any further.

Edit:
Looking more into it, I think it has to do with how I am storing the upload file. I am first storing the file uploaded to a tmp directory. After the file has been save, I call $Web->scan() to scan this cache directory. Is this process incorrect? Thanks

**Comment by shadowstriker15** [comment]
Answered my own question. I was under the impression that the $Web->scan() was scanning the cache directory so I was calling this after storing the upload, as mentioned in my previous comment. Making this call before even storing the upload fixed the issue and `delete_on_sight` is working as expected. Thank you and sorry for any confusion!

**Comment by Maikuolan** [comment]
Ah, cool. I didn't get any further with it at my end unfortunately, so I'm glad to hear you managed to figure it out at your end. :-)

I'm contemplating maybe reinforcing the documentation at some point with more clear details about how this works, and maybe even splitting that directive into several smaller directives at some point, to help deal specifically with uploads, with non-upload scans, options for whether to delete immediately or to take other, different kinds of actions, but that's something for another day and another issue anyway, I guess.
