### ISSUE TITLE
Embedded EICAR in .ppt & .pdf files is not detected

### ISSUE THREAD

**Issue by st-way** [Maikuolan/phpMussel#226]
### phpMussel version used
3.0.1

### Signatures version
All installed, latest from Git

### PHP SAPI used
litespeed

### PHP version installed
7.2.0

### Operating system used
Linux 3.10.0-962.3.2.lve1.5.36.el7.x86_64

---
## Issue
Hi,

I did some tests following the EICAR.txt fix (this is working now), and it seems that embedded EICAR in powerpoint and also in PDF are not detected as well. Is is a normal behavior ?

Thanks!

### Files
[EICAR pdf](http://sec.cs.tut.fi/horpa/h/data/eicar.pdf)
[EICARE PPT](https://github.com/mattias-ohlsson/eicar-standard-antivirus-test-files/raw/master/eicar-standard-antivirus-test-file-microsoft-powerpoint-action-macro-msgbox.ppt)

**Comment by Maikuolan** [comment]
In the sense that it's not a "bug" or a "false negative" per se, and in the sense that it's current anticipated behaviour, I'd call it "normal", but I wouldn't necessarily call it ideal, nor desirable. phpMussel's ability to isolate embedded objects/files from within PDFs/PPTs, in order to be able to scan those individual embeds independent of their containers, isn't so great yet, which is why it isn't currently detecting the embedded eicar within those files.

I plan to improve on that ability when I get some more time and figure out the best way to do it (or alternatively, if/when I can rope someone more knowledgeable than myself into helping me out with it).

To be sure I'm doing it properly, I'll probably need to find some proper specs for the formats and start reading through it all at some point. Looking at the raw data of the files in question, there are some obvious patterns in the data, so I can kind of intuit/guess how those embeds should/could be isolated relatively easily, but then, even if my intuited/guessed method happens to end up working perfectly with the particular files in question, I wouldn't know for sure whether it'll actually work properly for other files of the same format in other situations. Maybe I should just go ahead..? Not sure whether I should (it might seem a bit "hacky"..  '^.^). Though, I suppose, it can always just be rewritten at a later date, after having read through the specs properly. Anyway.. I'll think a little more on it when I get some time, do a little searching, see whether I can find anything to work with, etc.

**Comment by Maikuolan** [comment]
So.. Some progress has been made on the PDF front. :-)

For the moment, I went with the "hacky" approach, and it seems to be working as perfectly and as expected for the particular sample attached to this issue above. I tried creating some samples of my own, with various permutations (different PDF versions, different encoding, etc), and the results have varied quite a bit (about ~50/50 for phpMussel being able to catch them properly). I'll made a start of reading over the specs for the format, and I'll try to slowly improve on it when there's time, to gradually turn it into something a little less "hacky", and more capable of catching more, but I don't know how long that'll take (and of course, anyone willing to have a go at it is welcome to do so).

*v1: ([`3099a05`](https://github.com/phpMussel/phpMussel/commit/3099a051a52482d6b0ff8efa46d2acecffd644d5), [`de6fb58`](https://github.com/phpMussel/phpMussel/commit/de6fb58f8e8f197c2dc56051723c6131f1b96482)).*
*v2: ([`8adc049`](https://github.com/phpMussel/phpMussel/commit/8adc04976e282c91f48244da7a7c01395ed7e18c), [`3dcfc55`](https://github.com/phpMussel/phpMussel/commit/3dcfc550ecc282982105c6db09c93b888fcd3c6f)).*
*v3-Core: ([`d1db0ab`](https://github.com/phpMussel/Core/commit/d1db0ab870536a7aaec953eec136fc61eecfb5b2), [`c5136d7`](https://github.com/phpMussel/Core/commit/c5136d7603ef8a36775676c08c8f91895591e73e)).*

No progress on the PPT front yet.

**Comment by st-way** [comment]
Hello,

Awesome... thanks a lot ! Keep going!
