### ISSUE TITLE
[question] is it safe to update from v1 to v 3? 

### ISSUE THREAD

**Issue by neuropass** [Maikuolan/phpMussel#228]
I have the v1 branch as part of my application. Is it safe to jump to v3? if yes should I expect something to break? 

Thnaks!

**Comment by Maikuolan** [comment]
> Is it safe to jump to v3?

That somewhat depends on perspective.

From solely a *security* standpoint (i.e., not accounting for any API changes, any deprecations, any breaking changes, etc), jumping to v3 should be completely safe.

However, API changes, deprecations, and breaking changes all exist, and since we're talking in the context of phpMussel being implemented as part of your application, a direct jump from v1 to v3, *without* taking those changes into account, could possibly be somewhat unsafe.

Therefore..

> if yes should I expect something to break?

Yep. :-)

I plan to eventually list all those changes directly in the README documentation, at some point in the future, but I haven't done that yet.

But, if I was to briefly summarise it all: The primary aim of v3 is to more closely align phpMussel to the Composer way of doing things, to separate (where possible, and where it makes sense to do so) the various main (albeit distinct) parts of phpMussel (which, prior to v3, were all bundled together into the same package) into their own distinct, independent repositories, having the main repository (phpMussel/phpMussel) act as an orchestrator (from v3 onward) for those various parts (now all as Composer packages).

phpMussel from v3 onward is a 100% OOP-style project (so fully namespaced, PSR-4 compliant, etc and etc). That's one of the big changes to the API (since now, the implementation would be instantiating any needed phpMussel classes, as opposed to including any needed files to invoke or call closures, as was the case for v2 and prior -- detailed information about how to do that is documented in the current up-to-date documentation for v3).

phpMussel's tree structure has also changed. Since we're going for Composer's "vendor" approach, there's no more "vault" anymore. Instead, each "vendor" package contains "src" (for PHP files and any other pertinent "source" data), "l10n" (any pertinent YAML language data for the package), and "assets" (any *other* pertinent non-source assets, such as HTML files).

For any "writable" data (i.e., other things that would've previously been written to the vault, like the configuration files, logs data, quarantine, etc), paths can now be specified at instantiation (thus eliminating the need for there to be a "vault" anymore). That's something new, which didn't exist for v2 or prior.

Seeing as that in a Composer environment, most users rely on Composer to update everything, phpMussel's own internal updater doesn't exist anymore for v3 (so, no updates page at the front-end anymore). That's probably the most notable deprecation. Since components can now be updated via Composer, it mostly shouldn't be an issue.. but I haven't componentised the phpMussel signature files, so I guess, for now, that'll need to be done either via a separate SigTool implementation, or manually (though I'm still considering maybe building some other kind of way to update signature files automatically, if I can think up a way of doing it that plays nicely with Composer, and without bloating the implementation out with several dozen additional micro-components for Composer to deal with, which.. wouldn't be particularly elegant, I think). Language data has been somewhat demoted in the sense of it no longer being considered as distinct components, but bundled as needed directly into the affected components (i.e., core language data into the core package, front-end language data into the front-end package and so on). Similar deal with the "themes".

The front-end file manager has also been deprecated and removed, so from that perspective, v3 could be argued to be safer than v2 and prior, since now, even if an attacker theoretically managed to hack their way into the front-end, it would now be much more difficult than before to affect any actual changes to any of phpMussel's files via the front-end.

"Honeypot mode" is another deprecation (though, to my knowledge, nobody really used that feature anyway, so shouldn't really be a big deal for anyone).

Some unnecessary configuration directives have been deprecated and removed. `disable_cli` and `disable_frontend`, since the phpMussel CLI-mode and phpMussel Front-End each have their own repositories now (meaning that those configuration directives aren't needed anymore for v3, since users which don't want those particular features can simply forego installing the Composer packages corresponding to those features), and `disable_webfonts` (since I'd been planning on removing webfont support from phpMussel for a long time now, but since I figured that such a thing, in isolation, didn't really warrant releasing a new major version, I just held off doing it until I had additional reasons to start working on a new major version, so that I could sort it all out at the same time). I think maybe some others too.. but I don't recall offhandedly. I'll double-check it all tomorrow to confirm.

Front-end data like front-end accounts, sessions information, the cache, etc no longer has its own distinct file. Accounts are now bundled into the configuration file, sessions information now bundled alongside cache data, and the cache data configurable to be either handled by whatever configured extensions (e.g., APCu, Memcached, Redis, etc), or handled by a file explicitly specified at instantiation.

There's been various refactoring, minor performance improvements and such since v3 too, though not to an extent that I'd consider "game changing" or anything like that. The most directly noticeable performance improvements are probably with scanning in CLI-mode, I think. CLI-mode is definitely much, much faster, better, and reliable now, compared to before. Improvements elsewhere exist, but are relatively less noticeable.

Another big change: The "plugins" system utilised by v1 and v2 doesn't exist anymore from v3 onward, having been entirely superseded by the "events orchestrator". The "events orchestrator" already exists in v1 and v2, but was utilised by those major versions only for various internal mechanisms, such as the default logging procedures and two-factor authentication. However, since the events orchestrator was already capable of achieving anything that the plugins system could achieve, and since it was much cleaner and much more well-suited to the 100% OOP design of v3, I opted to just use that instead of the old plugins system, removing the old plugins system from v3 entirely. (I still refer to v3 plugins as "plugins", since it's easier to understand the intention of the plugins when thinking of them in that manner, though simply describing them as separate packages that hook into the events orchestrator would probably be more accurate now). This is something that probably isn't really important if you don't use any plugins, but would definitely be something to take note of if you happen to write custom phpMussel plugins of your own.

If jumping from v1 to v3, I would definitely recommend a fresh installation. Manually migrating step by step (i.e., keeping old configuration, old metadata, old settings, etc) is technically possible, but would take much more time than a fresh installation and would be possibly error-prone, due to the number of changes.

The next question: *Should* you jump to v3? Well.. I'm still maintaining both v1 and v2 at their own distinct branches, and I don't plan to end support for v2 within the immediate future, at least until it becomes necessary to do so, or at least until I have some kind of vague plans in place for v4 (which currently, I don't). Probably similar for v1. I've already marked v1 as "locked" (meaning, no more new big features to be added to it unless necessary, since any features newly added to phpMussel, I would be ideally more focusing towards v3, and back-porting across three different major versions can be a pain sometimes), but not yet as EoL, since it shouldn't be troublesome yet to fix any major bugs that might emerge in the immediate future, and the share of phpMussel users still using v1 at the moment is enough that ending support for it right now would definitely be too premature, I think. So, it's not yet absolutely necessary to do so.

How I would approach this:
- Is your application already, at this point in time, significantly integrated with, or built around Composer? If so, then jumping to v3 would 100% be worthwhile, and would be 100% beneficial to your application in the long run. If not, then..
- Do you plan for it to be so at some point in the future? Or are you already a Composer user? If so, then plan ahead for an eventual jump to v3, when you feel the time is right (e.g., for when you're ready to make your other changes alongside it).
- If not, or if you particularly want to avoid Composer, particularly don't like Composer, or particularly prefer the previous API (v1~v2), then just stick with v1 or v2.
- At this point, if it's a choice between v1 or v2.. Are you using PHP 7.2 or newer? If so, then jump to v2 (as long as you're sure that you definitely won't need phpMussel to interact with a PHP version older than that at any point in your environment).
- If using a PHP version prior to 7.2, or if phpMussel needs to interact with an older PHP version, then you'll need to stick to v1, since both v2 and v3 require at least PHP >= 7.2 (simplistic polyfills won't be possible, since there are some language constructs used in v2 and v3 which aren't supported by older PHP versions).
