### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by ghost** [Maikuolan/phpMussel#230]
I'm not really sure this is what I'm looking for but more a contact email. Anyway, I installed this on my website, which hosts a lot of user-created content for games (i.e. maps, mods etc),

I seem to be getting an awful lot of false positives. At first I accepted it was because they were applications such as .exe files, but recently it flagged a PDF file and there was nothing else in the submission.

Is there any way you can think of, of maybe calming this down a little bit?

I'm not sure what version I have, but I do know it was updated on 20 July 2020, so that's the one I have.

**Comment by Maikuolan** [comment]
Hi @chris98,

Could you provide some examples of some of messages shown by phpMussel when its detects the files, and what kinds of files are being detected when that happens? (phpMussel should normally show this quite prominently, like `Detected [this]! Detected [that]!` on the page).

Cheers.

**Comment by ghost** [comment]
I don't have that information to hand, unfortunately. But I will start logging a serialized response when I run scans, so that I can get back to you with it.

The kinds of files being detected are just things like PDF files, or game map files created by the user. I can send you the links so you can check them yourself if you'd like, but I don't really want to disclose any of this in a public setting.

**Comment by Maikuolan** [comment]
> but I don't really want to disclose any of this in a public setting.

Understandable. :-)

For now, just knowing the types of files and the specific detections triggered should be sufficient. If I'm unable to get to the bottom of it after reviewing that information, it's possible that I might end up needing to see the actual files in question, but just knowing the types of files and the specific detections triggered possibly might be enough, so we'll try just starting with that for moment.

I don't have any problem discussing this via email, if you'd prefer that. You can email me at (my username here at GitHub, all lower-cased) `@gmail.com`. I just don't like posting my literal email address anywhere directly, verbatim, due to spammers and other kinds of potential automated harassment that I could (and probably would) receive. I wouldn't describe it as a secret, though (after all, anyone with knowledge about Git, which is the system utilised here by GitHub, could figure it out simply by analysing any single one of my commits anyway). If there's anything sensitive or confidential contained within such emails, it should be noted that I also have a [PGP key](https://peegeepee.com/4FD870EC3B608E73CF87DB6D082E6BC1046FAB95), so it should be possibly to encrypt any such sensitive, confidential content via PGP prior to sending it (to prevent any unwanted snooping from third-parties during transmission, from Google, etc).

**Comment by Maikuolan** [comment]
Since OP now shows as "ghost", I'll go ahead and close this now.
