### ISSUE TITLE
File uploading throws error when switching to php-fpm

### ISSUE THREAD

**Issue by kashak88** [Maikuolan/phpMussel#235]
Ubuntu 20.04
PHP 7.1.33-52+ubuntu20.04.1+deb.sury.org+1 (cli)
php7.1-fpm                        7.1.33-52+ubuntu20.04.1+deb.sury.org+1
apache2                           2.4.57-1+ubuntu20.04.1+deb.sury.org+1
phpmussel v1.13.2

Hello, not a developer so please bear with me :)
We're switching from mod_php to fpm (mpm_event) and we're having issues with phpmussel throwing "This should not be accessed directly." when trying to upload a file. It works without issues with mod_php. One of our developers tracked it to phpmussel/vault/cli.php, in particular these lines:

```
/** Prevents execution from outside of CLI-mode. */
if (!$phpMussel['Mussel_sapi'] || !$phpMussel['Mussel_PHP']) {
    die('[phpMussel] This should not be accessed directly.');
}
```
However we do define it:
```
$phpMussel['Mussel_PHP'] = defined('PHP_BINARY') ? PHP_BINARY : '';
```
and also
```
$phpMussel['Mussel_sapi'] = !defined('Via-Travis') && (
    empty($_SERVER['REQUEST_METHOD']) ||
    substr(php_sapi_name(), 0, 3) === 'cli' || (
        empty($_SERVER[$phpMussel['IPAddr']]) &&
        empty($_SERVER['HTTP_USER_AGENT']) &&
        !empty($_SERVER['argc']) &&
        is_numeric($_SERVER['argc']) &&
        $_SERVER['argc'] > 0
    )
);
```

Could you point us in the right direction? Is it a known issue and was perhaps has been fixed? (I realize our version is outdated). Is it FPM misconfiguration?

Let me know if I'm missing something. Appreciate your help

**Comment by Maikuolan** [comment]
This particular problem shouldn't exist in v3, because unlike in v2 and earlier, in v3, phpMussel CLI's mode, front-end, and web interface (or "upload handler") aren't all using the same entrypoint. So, "resolved" as of the latest major version, but strictly speaking, not "fixed", as the change in question, rather than a bug-fix, is part of a major structural change implemented for phpMussel v3, and as with most "major" changes, isn't backwards-compatible, and so, hasn't been backported to v2 or earlier (thus "resolved" but not "fixed").

How amendable would you be to updating to v3? From a support perspective, I feel like that would be the most straightforward solution, given that the problem shouldn't exist for v3 at all. However, because there are numerous major differences between your current version (v1.13.2) and the current latest version (v3.3.5 as "stable", or v3.4.0 as "unstable"; I plan to tag/release v3.4.0 as "stable" in the near future though), particularly in regard to the actual process of installation, updating from your current version to the current latest version would involve a complete uninstall/reinstall, rather than simply adjusted a few files or settings here and there, and it would probably be best to review all available configuration to ensure everything remains configured according to your preferences, so could likely mean more work involved at your end for your developer.

Worth noting too, that although phpMussel v1 would work with PHP versions from 5.4 onward, both v2 and v3 require PHP 7.2 or later. I notice your currently used PHP version is 7.1.33, so updating to phpMussel v3 would require that you update your installed PHP version too. Depending on your exact setup, whether newer PHP versions work properly in your server environment, whether you have other software running which requires lower PHP versions and such, that might or mightn't be a problem.

Alternatively, modifying the phpMussel loader as to enforce explicitly that only what you want gets loaded (as opposed to everything just sharing the same entrypoint and leaving it up to phpMussel to decide what to do based on the context) should resolve the problem too, as long as that's something your developer is comfortable doing. That approach, you mightn't necessarily be getting the various bug-fixes and other changes implemented since after the time that your current installed version was first released, but it would probably also mean a less work involved for you and your developer, due to not needing to update PHP versions, not needing to reinstall phpMussel, etc. (Of course, either approach, I would always recommend performing backups beforehand, in case anything goes wrong).

**Comment by kashak88** [comment]
Thanks for the reply,
It's currently not feasible to upgrade php. The dev found the issue and it has to do with PHP_BINARY . CLI/mod_php returns it properly but FPM returns empty value. Hardcoding the binary to /usr/sbin/php-fpm7.1 solves the issue.

**Comment by Maikuolan** [comment]
Glad to hear the issue has been resolved. :-)
