### ISSUE TITLE
A video file blocking and detact as HTML.defacement

### ISSUE THREAD

**Issue by gorai-sunil** [Maikuolan/phpMussel#240]
Hi! When I scan a video file using web scan it blocks and detacts as HTML.defacement. While I have checked that video file with other anti-malware scan tools but there was no problem with the same file. Can you plz anyone help here?
![ZBB](https://github.com/user-attachments/assets/855edcc8-ec55-4cd4-b3fc-fe59c8620c15)

**Comment by Maikuolan** [comment]
I've pushed some updates to the signature files just now (in particular, the `phpmussel.ndb` signature file). Updating to the latest versions of the signature files should fix the problem. Let me know how it goes and if the problem persists. :-)

**Comment by gorai-sunil** [comment]
Thanks @Maikuolan. After updating the signature file it works. 
Can I know the exact reason for this issue?

**Comment by Maikuolan** [comment]
The particular signature responsible for blocking the file upload checked for the presense of a specific text string which was used frequently by a specific defacer/hacker back around ~2015 whenever they defaced a website, as a means of claiming responsibility for said defacements (and thus, checking for its presense was an easy way to detect any files affected by such defacements). Because said text string is very small (only 7 bytes in length), and video files tend to be very large, the risk of encountering false positives in video files and other, similarly large files due to said signature was relatively high. As it has been a number of years now since I'd last seen that particular text string actually being used anywhere, I felt the simplest and most prudent solution would be to remove the affected signature entirely. A handful of other signatures have also been updated or removed for similar reasons.

**Comment by gorai-sunil** [comment]
Hi @Maikuolan now I am facing one other kind of issue in another valid video file as below
![image](https://github.com/user-attachments/assets/27ef8784-f946-44a8-afdd-d5cc74a8eeb6)
Can you please help here?
