### ISSUE TITLE
 Why a video file Detected phpMussel-PHP.Shell.Function-01.A

### ISSUE THREAD

**Issue by gorai-sunil** [Maikuolan/phpMussel#241]
Hi! When I scan a video file using web scan it blocks and detacts as Detected phpMussel-PHP.Shell.Function-01.A. While I have checked that video file with other anti-malware scan tools but there was no problem with the same file. Can anyone please help here for its solution?
![image](https://github.com/user-attachments/assets/e3115d2a-868b-449d-8260-dd05f67fbcaf)

**Comment by Maikuolan** [comment]
That particular signature should only be being parsed in the first place for potential PHP files, so it seems to me that phpMussel is most likely misidentifying the file as a PHP file (or as a potential PHP file, at least), instead of correctly identifying it as an MP4 file.

Unlike the case for the previous false positive, in this case, the signature itself, when parsed correctly, is still relevant, and still important, so outright removing it isn't the best solution. Instead, I'm going to work on some changes today with the aim of preventing this misidentification from occurring, which should consequently prevent this false positive from occurring again.

I'll reply back again after I've committed some changes.

**Comment by gorai-sunil** [comment]
Hi @Maikuolan any updates on this issue, please?

**Comment by Maikuolan** [comment]
I've pushed some new releases just now (v3.5.2) which should fix the problem. Let me know how it goes. :-)

**Comment by gorai-sunil** [comment]
@Maikuolan Thanks a lot! It is working for me now.
